### ISSUE TITLE
computePositionFromScreenPoint does not calculate correct position - wrong function name?

### ISSUE THREAD

**Issue by basisbit** [NASAWorldWind/WorldWindJava#105]
the description of WorldWindowGLJPanel.getView().computePositionFromScreenPoint(x,y) states:

> Computes the intersection of a line originating from the eye point and passing through (x, y) with the Globe. Only the ellipsoid itself is considered; terrain elevations are not incorporated.

Because this function does not actually return the correct position for x and y screen coordinates when the view is panned, this function should either be fixed to include elevation data or needs to be renamed.
If you decide to rename the function or to do nothing, please explain an alternative solution to get the correct position.

**Comment by zglueck** [comment]
`computePositionFromScreenPoint` is functioning properly and as intended. As you noted, the documentation states the intersection is calculated with the ellipsoid and not terrain.

To determine an intersection from the screen point you need to access the Terrain object from the SceneController. The terrain object provides similar intersection methods as the view; however, you may need to provide a Line object representing a ray from the screen point.
