### ISSUE TITLE
WMS GetMap query parameters have incorrect case

### ISSUE THREAD

**Issue by johnk1** [NASAWorldWind/WorldWindJava#159]
### Description

Certain WMS servers will fail to return imagery based on WWJ's GetMap request. This is because the GetMap sends the request parameter field names (i.e., the part preceding the '=') in lower-case but the server requires upper-case. Quick review of the [WMS 1.1.1 spec ](http://cite.opengeospatial.org/OGCTestData/wms/1.1.1/spec/wms1.1.1.html#table.getmap) seems to show these should be in upper-case, so I think it is WWJ that is wrong here.

### Steps to Reproduce

1. Create a WMS connection to a server that requires upper-case query parameter field names
2. See that no WMS layer exists. In my case, I received the WMS Capabilities document each time a GetMap request was made

### Operating System and Version

Windows 10, WWJ 2.1.0

**Comment by johnk1** [comment]
Here's a workaround. It relies on [spring-web](https://mvnrepository.com/artifact/org.springframework/spring-web/5.1.2.RELEASE).

```
/**
 * A customization of the BasicLayerFactory to correctly create WMS query parameters, to workaround a WWJ bug.
 */
public class Bug159WorkaroundLayerFactory extends BasicLayerFactory {
    @Override
    protected Layer doCreateFromCapabilities(OGCCapabilities caps, AVList params) {
        WMSTiledImageLayer.wmsGetParamsFromCapsDoc((WMSCapabilities) caps, params);
        params.setValue(AVKey.TILE_URL_BUILDER, new UpperCaseWmsUrlBuilder(params));
        return new WMSTiledImageLayer(params);
    }

    public static class UpperCaseWmsUrlBuilder extends WMSTiledImageLayer.URLBuilder {
        UpperCaseWmsUrlBuilder(AVList params) {
            super(params);
        }

        @Override
        public URL getURL(Tile tile, String altImageFormat) throws MalformedURLException {
            // Get the normal URL but change all query parameters to upper-case for those servers that care.
            // Upper-case appears to comply with WMS specifications, though most WMS sources don't care.
            URL url = super.getURL(tile, altImageFormat);
            UriComponentsBuilder uriBuilder = UriComponentsBuilder.fromUriString(url.toExternalForm());
            MultiValueMap<String, String> repairedQueryParams = new LinkedMultiValueMap<>();
            for (Map.Entry<String, List<String>> query : uriBuilder.build().getQueryParams().entrySet()) {
                repairedQueryParams.put(query.getKey().toUpperCase(), query.getValue());
            }
            uriBuilder.replaceQueryParams(repairedQueryParams);
            return uriBuilder.build().toUri().toURL();
        }
    }
}
```

Then use this factory when creating your WMS layers:
`return (Layer) new Bug159WorkaroundLayerFactory().createFromConfigSource(capabilities, attributes);`

**Comment by wcmatthysen** [comment]
Hi there, according to the documentation WMS spec (see point 6.4.1):

> Parameter names shall not be case sensitive, but parameter values shall be case sensitive. In this document, parameter names are typically shown in uppercase for typographical clarity, not as a requirement.

So, according to the spec the request parameter-names are not case-sensitive, although the values are.

**Comment by johnk1** [comment]
Thanks @wcmatthysen. How'd I miss that?
