### ISSUE TITLE
Doesn't seem to work with Java 11

### ISSUE THREAD

**Issue by nicolas-van** [NASAWorldWind/WorldWindJava#181]
### Description

Worldwind doesn't seem to work at all with Java 11 (latest Java LTS, 8 will be in end of life at the end of 2020), at least under Ubuntu (I didn't tested Windows). Simple way to test is to use the demo app.

I suspect it is a problem related to JOGL which should be updated. Unfortunately doing so requires some changes in the code due to breaking changes introduced in JOGL since the version used by Worldwind.

### Steps to Reproduce

With Java 11 installed, try to run the demo using `run-demo.bash`.

**Expected behavior:** The demo launch successfully, like with Java 8.

**Actual behavior:** The application fails to launch with this error message:

```
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

**Reproduces how often:** 100%

### Operating System and Version

Ubuntu 18.04 (LTS)
Using openjdk-11 (default JDK under Ubuntu 18.04)

### Additional Information

Tested with Worldwind 2.1.0.

**Comment by trixon** [comment]
@nicolas-van WorldWind works just fine for me with Java 11, after I switched JRE/JDK that is.
I recommend using one from [AdoptOpenJDK](https://adoptopenjdk.net/index.html?variant=openjdk11&jvmVariant=hotspot
) or [Azul](https://www.azul.com/downloads/zulu-community/?&version=java-11-lts&os=ubuntu&os-details=Ubuntu&architecture=x86-64-bit&package=jdk).

Hope it helps

**Comment by trixon** [comment]
@nicolas-van I'm actually using the and old version of https://github.com/pcmehlitz/WorldWindJava-pcm, in order to use it in maven, and it's 2.1.0.
            <dependency>
                <groupId>com.github.pcmehlitz</groupId>
                <artifactId>worldwind-pcm</artifactId>
                <version>2.1.0.187</version>
            </dependency>

Running on Manjaro Linux, and tested on Windows 10 too.

**Comment by markpet49** [comment]
@nicolas-van Hi, thanks for reporting the issue. We are actively working on Java 11 compatibility to be released in the near future. The develop branch of WorldWind Java is Java 11 compatible and has upgraded JOGL libraries, but has not been fully tested. Regards, - Mark

**Comment by nicolas-van** [comment]
@markpet49 : good to know. Can't wait for the 2.2 ! 😄

**Comment by torishabhmehta** [comment]
I got the same error with openjdk 11.0.4 in mu ubuntu 18.04 system while running run-demo.bash script. Since  I have a project submission deadline, can I get a workaround?

**Comment by nicolas-van** [comment]
@torishabhmehta: If that may be useful to you the problem visibly comes from the JOGL library used by WorldWind that's not suitable anymore under JDK 11 (which seems logical, it's a version dating from 2014, we should not expect it to work flawlessly with a JDK from 2018).

I tried to simply upgrade the jars of JOGL to the latest version. Unfortunately that doesn't work as there was a breaking change somewhere in a minor version of JOGL where they renamed the `javax.media.opengl` package to something else.

So I can see three possible workarounds:

* Use the develop version of WorldWind that has an updated JOGL and has certainly been modified to support the breaking change. (Hoping it would be stable enough.)
* Try to find the latest version of JOGL before the breaking change and try to use it with the 2.1.0 version of WorldWind. If you're lucky that could work.
* Stick to JDK 8 for now (that's what I'm doing).

**Comment by nicolas-van** [comment]
As far as I can see the develop branch works fine with openjdk13 (I will assume it also works OK with jdk11). So I close this issue.
