### ISSUE TITLE
Question: state of development

### ISSUE THREAD

**Issue by nicolas-van** [NASAWorldWind/WorldWindJava#194]
Hello,

Could we know the current state of the development ? I noticed the NASA commitment message on the website but nothing seems to have changed since 4-5 months and we don't see any activity in this repository since.

My company is expecting a new release soon as we rely on WorldWind for one of our main products and we have more and more incompatibilities with the latest release from 2016.

Are you still working on this or should we attempt to fork this repository to make our own release(s) ?

Thanks in advance for taking the time to answer.

**Comment by PJHogan** [comment]
Nicolas, GREAT question!
And I have it from good sources that yes indeed MUCH progress has been made with both the Java and JavaScript versions of WorldWind! The issue slowing down the release of this freshened up codebase are some bureaucratic 'release' technicalities. But those are almost all handled. Expect to see some beautiful new code within a few weeks. And very sorry for the delay. And thanks for your interest and concern. We are all looking forward to some GOOD NEWS soon!!!

**Comment by PJHogan** [comment]
[https://images-na.ssl-images-amazon.com/images/I/61svq%2BqlevL._AC_SL1176_.jpg](url)

**Comment by PJHogan** [comment]
https://images-na.ssl-images-amazon.com/images/I/61svq%2BqlevL._AC_SL1176_.jpg

**Comment by markpet49** [comment]
@nicolas-van Hi, Adding to Patrick's response above. The develop branch is what we are working on releasing and should only see a very few changes prior to release. We haven't finalized testing on the code yet, but believe it is relatively solid. You can build the release artifacts yourself with the release-build.xml ant script included in the release.

**Comment by PJHogan** [comment]
https://images-na.ssl-images-amazon.com/images/I/61svq%2BqlevL._AC_SL1176_.jpg

**Comment by nicolas-van** [comment]
Thanks for the answer.
