### ISSUE TITLE
Non Resolving Link Target in README.md

### ISSUE THREAD

**Issue by chris-bishop** [NASAWorldWind/WorldWindJava#229]
Hello!

Firstly, let me thank NASA for these outstanding contributions to the Open Source Community, and of course for continuing to push humanity forward through innovation and exploration!

I was referring back to the README.md file to nav my way back in to some example code and reference material today, and happened to discover the following markdown link ref basically ==  `(Request) --> /dev/null` to "black hole":

https://www.github.com/NASAWorldWind/WorldWindJava/tree/develop/README.md#L31

```markdown
- [Java Demos](https://goworldwind.org/demos) has a complete list of example apps
```

I'm not sure if the site below was in fact the original intended target and has since migrated under a new DNS - however, in either case, given the context it seems they may make a worthy replacement :smile: 

https://live.osgeo.org/archive/10.0/en/quickstart/worldwindjava_quickstart.html

If I wasn't currently traveling and stuck with my phone only I would submit a PR to at least remove the non resolving endpoint, so I at least wanted to backlog an Issue.

When I finally return home if someone hasn't beat me to it I will do so for sure - would be the least I could do given all NASA does for the world!

To infinity and beyond!

Cheers,

[@chris-bishop](https://github.com/chris-bishop) - Git
[Chris Bishop](https://www.linkedin.com/in/chris-bishop-084b26a) - LinkedIn

**Comment by Beak-man** [comment]
Hello @chris-bishop. We fixed that outdated reference in the README a while ago but indeed we had some other hyperlinks in the project with references to the old website. PR #235 is submitted to address this. Thank you for the heads-up and the warm comments!

**Comment by chris-bishop** [comment]
Hey @Beak-man!

Apologies for only JUST now acknowledging your comment and [PR #235](https://github.com/NASAWorldWind/WorldWindJava/pull/235)!

And that's a big "Affirmative Ground Control!" (please excuse my overuse of Space puns - I have a pun sickness!) 

`README.md` links now all work as expected - thank you for taking the time to fix this - and for everything you and the team at NASA do for us!

👍🏼 💯 🥇
