### ISSUE TITLE
"Sea of Japan" is political controversial

### ISSUE THREAD

**Issue by marpet** [NASAWorldWind/WorldWindJava#232]
In World Wind the sea between Korea and Japan is labelled as "Sea of Japan".
This is not the best naming. Other maps use "Sea of Japan/East Sea"
Would be good if this would be fixed.
See: https://en.wikipedia.org/wiki/Sea_of_Japan_naming_dispute

This naming is shown when using the NASAWFSPlaceNameLayer implementation.

I tried to update the https://www.worldwindcentral.com/wiki/Placename_Errors page but it is locked.
This issue has also been reported some time ago in the forum.
https://forum.worldwindcentral.com/forum/archived-forums/worldwind-net-development/support/bug-reports/6045-name-error

**Comment by Beak-man** [comment]
Hi @marpet , thank you for bringing this to our attention. We inherit NGA naming conventions, and this geographical feature is labeled as "Sea of Japan" by the NGA. You can look it up at:

https://geonames.nga.mil/namesgaz/

**Comment by marpet** [comment]
Okay, I have reported this issue to them. 
We continue to use our workaround until the NGA might consider it.
