### ISSUE TITLE
SSL certification

### ISSUE THREAD

**Issue by kgokalp** [NASAWorldWind/WorldWindJava#260]
The SSL certificate for https://worldwind.arc.nasa.gov has expired. Are you planning to renew certificate?

**Comment by PJHogan** [comment]
How to re-establish? Or should I say how much?

**Comment by kgokalp** [comment]
It is the same issue as stated in issue #257.

**Comment by markpet49** [comment]
We had some certs expire yesterday, I believe they are all now renewed. The admins are in the process of automating the cert renewal, so hopefully this happens less frequently in the future.
