### ISSUE TITLE
SurfaceText Picking / Drag problem

### ISSUE THREAD

**Issue by gcheadley** [NASAWorldWind/WorldWindJava#28]
I'm noticing a issue with the class SurfaceText that appears to be picking / dragging related.  I am able to select a SurfaceText object and drag it once, and after that I can no longer pick / drag, get hover notifications, etc.  You can easily reproduce this issue by combining the SurfaceTextUsage.java example into the SimpleShapeDragging.java example. In other words, I added 
 
        SurfaceText surfaceText = new SurfaceText("Desolation Wilderness", Position.fromDegrees(38.9345, -120.1670, 0));
        layer.addRenderable(surfaceText);
 
in the constructor, and then just set the initial coordinates to zoom to that location in main() for convenience:
 
        Configuration.setValue(AVKey.INITIAL_LATITUDE, 38.9345);
        Configuration.setValue(AVKey.INITIAL_LONGITUDE, -120.1670);
        Configuration.setValue(AVKey.INITIAL_ALTITUDE, 50000);
 
You will see that you can hover over, select, deselect, but as soon as you drag it and deselect you can’t select and drag again.

Thanks
Garrett

**Comment by zglueck** [comment]
@gcheadley thanks, with your example I was able to duplicate the behavior.

**Comment by pdavidc** [comment]
We've pushed changes to the develop branch that repair this issue. See commit 580e040.

**Comment by wcmatthysen** [comment]
Hi @gcheadley, if this is still a bug, could you open an issue at the community-fork of WorldWind: https://github.com/WorldWindEarth/WorldWindJava
