### ISSUE TITLE
EGM96.java interpolation code is wrong

### ISSUE THREAD

**Issue by samilkorkmaz** [NASAWorldWind/WorldWindJava#3]
In <a href = "https://github.com/NASAWorldWind/WorldWindJava/blob/master/src/gov/nasa/worldwind/util/EGM96.java">EGM96.java</a>, method getOffset(), the interpolation portion has an error. To correct it, topRow and bottomRow indices have to be swapped when calling getPostOffset() function.

For details, see my blog post here: http://samilkorkmaz.blogspot.com/2016/03/error-in-nasa-code.html

**Comment by zglueck** [comment]
@samilkorkmaz Thanks for finding this one and the informative blog post! I just pushed commit 08e9201 which implements the fix you recommended and includes some unit testing to verify the getOffset method.
