### ISSUE TITLE
HTTPS map services

### ISSUE THREAD

**Issue by pdavidc** [NASAWorldWind/WorldWindJava#32]
Migrate the NASA map services used by World Wind Java to the HTTPS protocol.

Default Layers:
- [x] Blue Marble May 2004 (BMNGWMSLayer2.xml)
- [x] i-cubed Landsat (LandsatI3WMSLayer2.xml)
- [x] USDA NAIP (USDANAIPWMSImageLayer.xml) 
- [ ] <del>USDA NAIP USGS (USDANAIPUSGSWMSImageLayer.xml) [nationalmap.gov] </del> _service decommissioned_
- [x] MS Virtual Earth Aerial (MSVirtualEarthAerialLayer.xml)
- [x] Bing Imagery (BingImagery.xml)
- [x] USGS Topographic Maps 1:250K (USGSTopoLowResLayer.xml)
- [x] USGS Topographic Maps 1:100K (USGSTopoMedResLayer.xml)
- [x] USGS Topographic Maps 1:24K (USGSTopoHighResLayer.xml)
- [ ] <del>USGS Urban Area Ortho (USGSUrbanAreaOrthoLayer.xml) [ww25/tile?104]</del> _deprecated; service unavailable_
- [x] Political Boundaries (CountryBoundariesLayer.java)
- [x] Open Street Map (OpenStreetMap.xml)
- [x] Earth at Night (EarthAtNightLayer.xml)
- [x] Place Names (NASAWFSPlaceNameLayer.java)

Other Layers:
- [x] FAA Sectionals (AlaskaFAASectionals.xml)
- [x] Blue Marble 200405 - 256 (BMNG256.xml)
- [x] Blue Marble (WMS) 2004 (BMNGWMSLayer.xml)
- [x] i-cubed Landsat  (Landsat256.xml)
- [x] i-cubed Landsat (LandsatI3WMSLayer.xml)
- [x] MS Virtual Earth Hybrid (MSVirtualEarthHybridLayer.xml)
- [x] MS Virtual Earth Roads (MSVirtualEarthRoadsLayer.xml)
- [ ] <del>USGS Digital Ortho (USGSDigitalOrthoLayer.xml) [ww25/tile?101]</del> _deprecated; service unavailabe_
- [x] Scankort Denmark (ScankortDenmarkImageLayer.xml) [data/wms]
- [x] MILSTD2525 Icon Retriever (worldwind.xml / MilStd2525Constants.java)

Default Elevations:
- [x] USA 10m, World 30m, Ocean 900m (EarthElevations2.xml)

Other Elevations:
- [x] USA 10m, World 30m, Ocean 900m (EarthElevations256.xml)
- [x] Aster V2 (AsterWCS.xml) [ww26/wcs]
- [x] Earth Elevation Model (SRTM30, SRTM3, NED 10m, BIL16) (EarthMergedElevationModel.xml)
- [x] USA 10m, World 30m, Ocean 900m (EarthElevatioModelAsBil16.xml)
- [x] Earth Elevation Model (USA 10m, WordWide 30m, Ocean 900m)  (EarthElevatioModelAsBil32.xml)
- [x] Scankort Denmark DSM (ScankortDenmarkDSMElevationModel.xml) [data/elev]

Other Servers We Reference:
- [x] neowms.sci.gsfc.nasa.gov/wms/wms Used in the EuroGeossApp and WMSLayerManager in the worldwindx package.
- [x] eoimages.gsfc.nasa.gov/ve//1438/earth_lights_lrg.jpg Used in the RemoteSurfaceImage example
- [ ] <del>23.21.170.207/geodab-dswg/services/cswisogeo Used in the EuroGeossApp in the worldwindx package.</del>

**Comment by emxsys** [comment]
### worldwind22.arc.nasa.gov/geoserver/wms fails with 502 proxy error.
Used in CountryBoundariesLayer.xml

https://worldwind22.arc.nasa.gov/geoserver/wms?SERVICE=wms&REQUEST=GetCapabilities

    Proxy Error
    The proxy server received an invalid response from an upstream server.
    The proxy server could not handle the request GET /geoserver/wms.
    Reason: Error reading from remote server

**Comment by emxsys** [comment]
### worldwind26.arc.nasa.gov/wms fails with 404 Not Found error

Used in EarthElevations2.xml

https://worldwind26.arc.nasa.gov/wms?SERVICE=wms&REQUEST=GetCapabilities

**Comment by emxsys** [comment]
### raster.nationalmap.gov/arcgis/services/Combined/USGS_EDC_Ortho_NAIP/MapServer/WMSServer fails with connection not secure error.

The http protocol fails with a 404 Not Found error.

Used in USDANAIPUSGSWMSImageLayer.xml


https://raster.nationalmap.gov/arcgis/services/Combined/USGS_EDC_Ortho_NAIP/MapServer/WMSServer?SERVICE=wms&REQUEST=GetCapabilities

See https://raster.nationalmap.gov/arcgis/rest/services/Orthoimagery for other services to consider.

**Comment by emxsys** [comment]
### worldwind25.arc.nasa.gov/tile/tile.aspx fails with 404 Not Found error

Used in USGSDigitalOrthoLayer.xml

https://worldwind25.arc.nasa.gov/tile/tile.aspx

**Comment by zglueck** [comment]
http://23.21.170.207/geodab-dswg/services/cswisogeo no longer resolves to an ip

Used in the EuroGeossApp in the worldwindx package.

**Comment by zglueck** [comment]
http://neowms.sci.gsfc.nasa.gov/wms/wms does not support https connections

Used in the EuroGeossApp in the worldwindx package.

**Comment by emxsys** [comment]
### worldwind22.arc.nasa.gov/geoserver/wfs fails with a 502 proxy error

Used in Placenames layer

https://worldwind22.arc.nasa.gov/geoserver/wfs?version=1.0.0&TypeName=topp:wpl_mountainsvalleys&Request=GetFeature&Service=WFS&OUTPUTFORMAT=GML2-GZIP&BBOX=-135.0,45.0,-112.5,67.5

**Comment by emxsys** [comment]
NAIP GetMap request fails. 
NAIP layer is not in https://worldwind47.arc.nasa.gov/wms?SERVICE=wms&REQUEST=GetCapabilities
Used in USDANAIPWMSImageLayer.xml

https://worldwind47.arc.nasa.gov/wms?service=WMS&request=GetMap&version=1.3.0&crs=CRS:84&layers=NAIP&styles=&transparent=TRUE&format=image/dds&width=512&height=512&bbox=-118.6875,34.3125,-118.125,34.875

**Comment by emxsys** [comment]
https://data.worldwind.arc.nasa.gov/wms?service=WMS&request=GetMap&version=1.3.0&crs=CRS:84&layers=Scankort&styles=&transparent=TRUE&format=image/dds&width=512&height=512&bbox=13.5,56.25,15.75,58.5 generates a 400 bad request error.

Used by ScankortDenmarkImageLayer.xml

The Scankort layer is not listed in the GetCapabilities document.

**Comment by emxsys** [comment]
Using the ScankortDenmarkDSMElevationModel.xml elevation model generates an exception:
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at gov.nasa.worldwindx.examples.layermanager.ElevationModelManagerPanel.isUpToDate(ElevationModelManagerPanel.java:130)
	at gov.nasa.worldwindx.examples.layermanager.ElevationModelManagerPanel.fill(ElevationModelManagerPanel.java:91)
	at gov.nasa.worldwindx.examples.layermanager.ElevationModelManagerPanel.<init>(ElevationModelManagerPanel.java:48)
	at gov.nasa.worldwindx.examples.LayerPanel.<init>(LayerPanel.java:33)
	at gov.nasa.worldwindx.examples.ApplicationTemplate$AppFrame.initialize(ApplicationTemplate.java:115)
	at gov.nasa.worldwindx.examples.ApplicationTemplate$AppFrame.<init>(ApplicationTemplate.java:90)
	at gov.nasa.worldwindx.examples.WMSLayerManager$AppFrame.<init>(WMSLayerManager.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at gov.nasa.worldwindx.examples.ApplicationTemplate.start(ApplicationTemplate.java:309)
	at gov.nasa.worldwindx.examples.WMSLayerManager.main(WMSLayerManager.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by emxsys** [comment]
USGS Digital Ortho layer fails (USGSDigitalOrthoLayer.xml).
https://worldwind25.arc.nasa.gov/tile/tile.aspx?T=101&L=3&X=629&Y=1227 generates a 404 Not Found error.

**Comment by zglueck** [comment]
While going through the links listed in commented out source of worldwindx, I updated the link to https for convenience if the link supported https. There were a few dead links, I didn't change them at all, I figure the full address may provide some context as to the original link.

**Comment by emxsys** [comment]
The USGS 250K and USGS 100K Topo layers have too many levels defined (19).  A 4 sq kilometer bulk download attempts to download/create a 10GB+ tile set for each of these low resolution maps.  Less than 10MB was the expected size.

**Comment by emxsys** [comment]
It looks like The National Map just dropped our NAIP layer set: http://raster.nationalmap.gov/arcgis/services/Orthoimagery/USGS_EROS_Ortho_NAIP/ImageServer/WMSServer?request=GetCapabilities&service=WMS

Here's an alternative: http://raster.nationalmap.gov/arcgis/services/Orthoimagery/USGS_EROS_Ortho_NAIP_SCALE/ImageServer/WMSServer?request=GetCapabilities&service=WMS

Here's the available sets: http://raster.nationalmap.gov/arcgis/rest/services/Orthoimagery

**Comment by emxsys** [comment]
To reduce the load on the server hosting the USGS Topo layers, and to limit the size of a bulk download, I adjusted the NumLevels count in the USGSTopoLowResLayer.xml, USGSTopoMedResLayer.xml and USGSTopoHighResLayer.xml files from the default 19 to 10, 10, and 13 respectively.

**Comment by emxsys** [comment]
Alternatives and additions from the USGS National Map to consider with regard to our hosted USGS Topos:

### USGS DRGs
A single layer comprised of 24K, 100K and 250K scanned topogragraphic maps.
http://raster.nationalmap.gov/arcgis/rest/services/Scanned_Maps
http://raster.nationalmap.gov/arcgis/services/Scanned_Maps/USGS_EROS_DRG_SCALE/ImageServer/WMSServer?request=GetCapabilities&service=WMS
![image](https://cloud.githubusercontent.com/assets/191515/20973925/4fa5df0a-bc4f-11e6-93c9-7f90affb5fe7.png)

### USGS Topo Basemaps
The new vector-based topographic maps from the USGS
https://basemap.nationalmap.gov/arcgis/rest/services/USGSTopo/MapServer
https://basemap.nationalmap.gov/arcgis/services/USGSTopo/MapServer/WMSServer?request=GetCapabilities&service=WMS
![image](https://cloud.githubusercontent.com/assets/191515/20974244/6336be62-bc50-11e6-9a30-22f8dcc2ebbf.png)
![image](https://cloud.githubusercontent.com/assets/191515/20974334/b04e7172-bc50-11e6-8538-968a680f8f47.png)

**Comment by PJHogan** [comment]
Bruce, yes, I noticed those earlier too.
Can WorldWind access those servers now?

**Comment by emxsys** [comment]
### USGS National Map Orthoimagery Map Services Transition and Other Map Service Changes
https://www.usgs.gov/news/usgs-national-map-orthoimagery-map-services-transition-and-other-map-service-changes

_Snippet:_

> Release Date: November 1, 2016
> 
> As part of The National Map transition to cloud hosting, several of the National Map NAIP Orthoimagery Services will be provided under new URLs.
> 
> On or about December 2, National Map Orthoimagery web map services, which display U. S. Department of Agriculture National Agricultural Imagery Program (NAIP) orthoimagery, are planned to be served from new URLs. These new URLs have been available and running in parallel for many months and most applications have already made the change to the new replacement services. In addition, as part of this transition, USGS legacy Digital Raster Graphic (DRG) or “Scanned Map” service will also be retired.
> 
> The National Map uses NAIP imagery as a key component of its US Topo map products. As part of the offerings associated with the product, it also provides imagery compressed files for download and imagery web map services for visualization in applications. These imagery services and data download provide an imagery base that supplements the associated US Topo GIS-based ‘Topo Map Vector Data Product’. The imagery web map services or imagery downloaded from TNM Downloader may both be used along with TNM vector products in the ‘Topo TNM Style Template’, providing GIS basemap layers and data in the cartographic style and layout of the US Topo maps.
> 
> These dynamic imagery services are designed to provide visualization from local to national scales for a variety of use cases. The replacement ‘Imagery - 1 meter (plus)’ service will contain NAIP orthoimagery along with other High Resolution Orthoimagery (HRO) to fill in areas where NAIP is not flown.  Some of the services listed below are scale-dependent, drawing only at the largest scales (below 18K scale), to facilitate zooming in past the levels currently supported in the faster USGS tile cached ‘Imagery Basemap’ service.  These capabilities are being maintained through the new URLs listed below.
>

**Comment by emxsys** [comment]
All NASA hosted map and elevation services have been converted to HTTPS.  

Decommissioned WMS services discovered in this process have been removed from the default layer list (config/worldwind.layers.xml) and marked as deprecated in the corresponding layer configuration file.  

The configuration files for decommissioned services remain in the SDK to satisfy clients that may have existing caches referencing these layers.
