### ISSUE TITLE
WorldWind server returned "application/x-qgis" content type for .shp and .shx files

### ISSUE THREAD

**Issue by emxsys** [NASAWorldWind/WorldWindJava#35]
worldwind.arc.nasa.gov returned a content type of "application/x-qgis" for .shp and .shx extensions.  The Shapefile class expected "application/shp" and "application/shx" respectively.

https://worldwind.arc.nasa.gov/java/apps/springfield/SPR_UGB.shp

**Comment by pdavidc** [comment]
The Apache configuration for worldwind.arc.nasa.gov returned the incorrect Q-Gis application MIME type for ESRI shapefiles ending with .shp and .shx. The apache server at worldwind.arc.nasa.gov now returns a null MIME type for shapefiles.
