### ISSUE TITLE
Where can I find license?

### ISSUE THREAD

**Issue by Nominalista** [NASAWorldWind/WorldWindJava#4]
I'm kindly asking for indication of license context.

**Comment by yuripourre** [comment]
http://www.worldwindcentral.com/wiki/NOSA

**Comment by PJHogan** [comment]
http://ti.arc.nasa.gov/opensource/nosa/

**Comment by Nominalista** [comment]
Thank you.

**Comment by basisbit** [comment]
please put some license information into the git repository. This is especially crucial for when other open source developers create pull requests and then they get accepted. Currently the license on the external website would not cover that additional work independantly from what that license might state. This for example prevents me from doing pull requests for bugfixes.

**Comment by zglueck** [comment]
The license for World Wind is in the repo, titled: NASA_Open_Source_Agreement_1.3.txt, which is identical to the externally linked site mentioned above.

Licenses for supporting libraries are also provided, typically with word LICENSE included in the filename.

**Comment by PJHogan** [comment]
https://opensource.org/licenses/NASA-1.3
http://ti.arc.nasa.gov/opensource/nosa/

**Comment by pdavidc** [comment]
We've added a standard LICENSE file to the World Wind Java repository, and have included a license section in README.md.
